#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Tomasz Fiedoruk
# Generates src/helpers/biper/BiperAppAsset.h from biper-app.html.
# The panel reaches the browser COMPRESSED. Not to save flash — one copy sits
# there either way — but to save the phone: the full file over the cube's Wi-Fi,
# on every visit, on a single-core device with no cache. gzip cuts it by ~63%.
# We compress HERE and not on the cube: the ESP32 has neither the time nor the
# RAM for it, and the file is fixed, so build-time compression is free.
import gzip
import pathlib
here = pathlib.Path(__file__).parent
source = (here / "biper-app.html").read_bytes()
# mtime=0: without it every run of the generator produces different bytes and
# the repository shows a diff where nothing actually changed.
data = bytearray(gzip.compress(source, compresslevel=9, mtime=0))
# Byte 9 of the gzip header is the OS field, and CPython writes a different
# value per platform (macOS: 255 "unknown", Linux: 3 "Unix"). The CI gate
# compares the generated header byte for byte, so the result has to be
# identical everywhere — we pin the OS field.
data[9] = 3
data = bytes(data)
out = here / "../../src/helpers/biper/BiperAppAsset.h"
rows = []
for i in range(0, len(data), 16):
    rows.append(",".join(str(b) for b in data[i:i+16]))
out.write_text(
    "// SPDX-License-Identifier: MIT\n"
    "// Copyright (c) 2026 Tomasz Fiedoruk\n"
    "// GENERATED by biper/app/gen-asset.py from biper/app/biper-app.html — do not edit.\n"
    "// Payload is GZIP-COMPRESSED; app_get() must send Content-Encoding: gzip.\n"
    "#pragma once\n#include <stdint.h>\n#include <stddef.h>\n"
    f"static const size_t BIPER_APP_HTML_LEN = {len(data)};\n"
    "static const uint8_t BIPER_APP_HTML[] PROGMEM = {\n"
    + ",\n".join(rows) + "\n};\n")
print(f"OK {len(source)} B -> gzip {len(data)} B "
      f"({100 - 100 * len(data) // len(source)}% smaller) -> {out.resolve()}")
