#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Tomasz Fiedoruk
# Generates src/helpers/biper/BiperFontAsset.h from the woff2 subsets.
# The fonts are served as SEPARATE HTTP resources rather than base64 inside the
# HTML: base64 inflates them by 33%, and the browser caches them anyway after
# the first visit to the panel.
import pathlib, sys

# Directory holding the subsets. A hard-coded path into a private disk made
# this generator unrunnable for anybody else — and leaked the disk layout.
# By default we look inside the repository; otherwise: gen-fonts.py <dir>.
SOURCE = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else (
    pathlib.Path(__file__).resolve().parents[2] / "fonts")
FILES = [
    ("next",      "atkinson-next-latin.woff2"),
    ("next-ext",  "atkinson-next-latin-ext.woff2"),
    ("mono",      "atkinson-mono-latin.woff2"),
    ("mono-ext",  "atkinson-mono-latin-ext.woff2"),
    ("black",     "archivo-black-latin.woff2"),
    ("black-ext", "archivo-black-latin-ext.woff2"),
]
out = pathlib.Path("src/helpers/biper/BiperFontAsset.h")
# LICENCE HEADER — READ THIS BEFORE YOU CHANGE IT.
# This output file is NOT ours under MIT. The payload is 97 kB of three
# typefaces under the SIL Open Font License 1.1, and the firmware
# REDISTRIBUTES them: the panel fetches them from the cube over /f/*.woff2,
# so every phone receives a copy of the font. OFL 1.1 is explicit: "The fonts
# and derivatives, however, cannot be released under any other type of
# license." An earlier header claimed MIT and our copyright over somebody
# else's work — that was untrue even in a private repository.
# The generator code stays MIT; the licence here covers the DATA it emits.
buf = ["// SPDX-License-Identifier: OFL-1.1",
       "// GENERATED by biper/app/gen-fonts.py — do not edit.",
       "//",
       "// This file embeds subsetted font data licensed under the",
       "// SIL Open Font License 1.1. Full licence text: fonts/OFL-1.1.txt",
       "//",
       "//   Atkinson Hyperlegible Next — Copyright 2020-2024",
       "//     The Atkinson Hyperlegible Next Project Authors",
       "//   Atkinson Hyperlegible Mono — Copyright 2020-2024",
       "//     The Atkinson Hyperlegible Mono Project Authors",
       "//   Archivo Black — Copyright 2017 The Archivo Black Project Authors",
       "//",
       "// The generator itself (biper/app/gen-fonts.py) is MIT,",
       "// Copyright (c) 2026 Tomasz Fiedoruk. The embedded font data is not.",
       "#pragma once", "#include <stdint.h>", "#include <stddef.h>", ""]
table, total = [], 0
for name, file in FILES:
    d = (SOURCE / file).read_bytes()
    total += len(d)
    sym = "BIPER_F_" + name.upper().replace("-", "_")
    buf.append(f"static const uint8_t {sym}[] PROGMEM = {{")
    for i in range(0, len(d), 20):
        buf.append(",".join(str(b) for b in d[i:i+20]) + ",")
    buf.append("};")
    buf.append(f"static const size_t {sym}_LEN = {len(d)};")
    buf.append("")
    table.append(f'  {{"/f/{name}.woff2", {sym}, {sym}_LEN}},')
buf += ["struct BiperFont { const char* path; const uint8_t* data; size_t len; };",
        "static const BiperFont BIPER_FONTS[] = {", *table, "};",
        f"static const size_t BIPER_FONTS_N = {len(FILES)};", ""]
out.write_text("\n".join(buf))
print(f"OK {total} B from {len(FILES)} files -> {out} ({out.stat().st_size//1024} kB header)")
